# patches
# Each entry in this list should resolve to
# a partial or complete resource definition file.
namespace: prod-REPLACE_ME_APP_NAME
images:
- name: REPLACE_ME_APP_NAME
  newName: REPLACE_ME_AWS_ACCOUNT_ID.dkr.ecr.REPLACE_ME_AWS_REGION.amazonaws.com/REPLACE_ME_APP_NAME
  newTag: ce293dbb114ede3ab0f5f3a177d79a29c235c848
patches:
- path: patch-env-from.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
- external-secret.yaml

