apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: REPLACE_ME_APP_NAME
spec:
  rules:
    - host: api.REPLACE_ME_APP_NAME.com
      http:
        paths:
          - backend:
              service:
                name: REPLACE_ME_APP_NAME
                port:
                  number: 80
            path: /
            pathType: ImplementationSpecific
  tls:
    - hosts:
      - api.REPLACE_ME_APP_NAME.com
      secretName: api.REPLACE_ME_APP_NAME.com
