apiVersion: v1
kind: Service
metadata:
  name: REPLACE_ME_APP_NAME
  annotations: 
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: http
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "https"
spec:
  ports:
  - name: http
    port: 80
    targetPort: REPLACE_ME_PORT
  - name: https
    port: 443
    targetPort: REPLACE_ME_PORT
  - name: api
    port: REPLACE_ME_PORT
    targetPort: REPLACE_ME_PORT
  type: ClusterIP
  selector:
    app.kubernetes.io/name: REPLACE_ME_APP_NAME
