apiVersion: 'kubernetes-client.io/v1'
kind: ExternalSecret
metadata:
  name: REPLACE_ME_APP_NAME-secrets
spec:
  backendType: systemManager
  data:
    - key: /REPLACE_ME_APP_NAME/qa/OPENAI_API_KEY
      name: OPENAI_API_KEY
    - key: /REPLACE_ME_APP_NAME/qa/COUPA_INSTANCE
      name: COUPA_INSTANCE
    - key: /REPLACE_ME_APP_NAME/qa/TOKEN_DATA
      name: TOKEN_DATA
    - key: /REPLACE_ME_APP_NAME/qa/GMAIL_API_CREDENTIALS
      name: GMAIL_API_CREDENTIALS
    - key: /REPLACE_ME_APP_NAME/qa/AWS_BUCKET_NAME
      name: AWS_BUCKET_NAME
    - key: /REPLACE_ME_APP_NAME/qa/AWS_ACCESS_KEY
      name: AWS_ACCESS_KEY
    - key: /REPLACE_ME_APP_NAME/qa/AWS_SECRET_ACCESS_KEY
      name: AWS_SECRET_ACCESS_KEY
    - key: /REPLACE_ME_APP_NAME/prod/AWS_ACCESS_KEY
      name: SES_AWS_ACCESS_KEY
    - key: /REPLACE_ME_APP_NAME/prod/AWS_SECRET_ACCESS_KEY
      name: SES_AWS_SECRET_ACCESS_KEY
    - key: /REPLACE_ME_APP_NAME/qa/SQS_URL
      name: SQS_URL
    - key: /REPLACE_ME_APP_NAME/qa/PROCESSING_API_URL
      name: PROCESSING_API_URL
    - key: /REPLACE_ME_APP_NAME/qa/AWS_REGION
      name: AWS_REGION
    - key: /REPLACE_ME_APP_NAME/qa/SOURCE_ARN
      name: SOURCE_ARN
    - key: /REPLACE_ME_APP_NAME/qa/GSHEET_KEY
      name: GSHEET_KEY
    - key: /REPLACE_ME_APP_NAME/qa/MONGO_URI
      name: MONGO_URI
    - key: /REPLACE_ME_APP_NAME/qa/ENV
      name: ENV
    - key: /REPLACE_ME_APP_NAME/qa/VITE_API_URL
      name: VITE_API_URL             
    - key: /REPLACE_ME_APP_NAME/qa/VITE_LOGO_CLICK_URL
      name: VITE_LOGO_CLICK_URL
    - key: /REPLACE_ME_APP_NAME/qa/VITE_GOOGLE_CLIENT_ID
      name: VITE_GOOGLE_CLIENT_ID
    - key: /REPLACE_ME_APP_NAME/qa/VITE_GOOGLE_CLIENT_SECRET
      name: VITE_GOOGLE_CLIENT_SECRET
    - key: /REPLACE_ME_APP_NAME/qa/VITE_BYPASS_PMC_VALIDATION
      name: VITE_BYPASS_PMC_VALIDATION 
    - key: /REPLACE_ME_APP_NAME/qa/AUTH0_DOMAIN
      name: AUTH0_DOMAIN
    - key: /REPLACE_ME_APP_NAME/qa/AUTH0_CLIENT_ID
      name: AUTH0_CLIENT_ID
    - key: /REPLACE_ME_APP_NAME/qa/AUTH0_CLIENT_SECRET
      name: AUTH0_CLIENT_SECRET
    - key: /REPLACE_ME_APP_NAME/qa/RESMAN_API_KEY
      name: RESMAN_API_KEY
    - key: /REPLACE_ME_APP_NAME/qa/RESMAN_INTEGRATION_PARTNER_ID
      name: RESMAN_INTEGRATION_PARTNER_ID
    - key: /REPLACE_ME_APP_NAME/qa/RESMAN_ACCOUNT_ID
      name: RESMAN_ACCOUNT_ID
    - key: /REPLACE_ME_APP_NAME/qa/RESMAN_TEST_PROPERTY_ID
      name: RESMAN_TEST_PROPERTY_ID
    - key: /REPLACE_ME_APP_NAME/qa/APP_URL
      name: APP_URL