apiVersion: apps/v1
kind: Deployment
metadata:
  name: REPLACE_ME_APP_NAME
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: REPLACE_ME_APP_NAME
  template:
    metadata:
     labels:
        app.kubernetes.io/name: REPLACE_ME_APP_NAME